In [1]:
import pandas as pd
df_nykaa=pd.read_csv(r"C:\project placement\csv dataset raw\nykaa_campaign_data.csv")
df_purplle=pd.read_csv(r"C:\project placement\csv dataset raw\purplle_campaign_data.csv")
df_tira=pd.read_csv(r"C:\project placement\csv dataset raw\tira_campaign_data.csv")

In [2]:
df_nykaa.columns=df_nykaa.columns.str.lower()
df_purplle.columns=df_nykaa.columns.str.lower()
df_tira.columns=df_nykaa.columns.str.lower()

In [3]:
df_nykaa["date"]=pd.to_datetime(df_nykaa.date ,format='mixed')
df_purplle["date"]=pd.to_datetime(df_purplle.date ,format='mixed')
df_tira["date"]=pd.to_datetime(df_tira.date ,format='mixed')

In [4]:
#we can see the channel_used contains multiple value in single row
df_nykaa

,campaign_id,campaign_type,target_audience,duration,channel_used,impressions,clicks,leads,conversions,revenue,acquisition_cost,roi,language,engagement_score,customer_segment,date,brand
0,NY-CMP-1000,Social Media,College Students,21,"WhatsApp, YouTube",57804,6156,3616,2355,1867515,111.03,6.14,Hindi,20.98,College Students,2025-04-29,Nykaa
1,NY-CMP-1001,Paid Ads,Tier 2 City Customers,18,YouTube,91801,3321,1971,1357,1046247,180.83,3.26,Hindi,7.24,College Students,2025-06-04,Nykaa
2,NY-CMP-1002,Influencer,Youth,23,"WhatsApp, Google, YouTube",15536,2182,952,755,197055,90.60,1.88,English,25.03,College Students,2025-01-14,Nykaa
3,NY-CMP-1003,Email,Working Women,18,"YouTube, Facebook, Instagram",88114,8413,2231,947,376906,249.07,0.60,Hindi,13.15,College Students,2025-04-06,Nykaa
4,NY-CMP-1004,Paid Ads,College Students,10,"Facebook, Instagram",96871,3743,2060,1258,518296,228.60,0.80,Hindi,7.29,Tier 2 City Customers,2024-12-29,Nykaa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55550,NY-CMP-56550,SEO,Youth,16,"Instagram, Email",31041,3849,1012,639,162945,374.90,-0.32,Tamil,17.72,Tier 2 City Customers,2025-02-16,Nykaa
55551,NY-CMP-56551,Paid Ads,Tier 2 City Customers,26,Facebook,27335,3715,2184,1006,792728,56.38,12.98,English,25.26,Premium Shoppers,2024-11-18,Nykaa
55552,NY-CMP-56552,Influencer,Tier 2 City Customers,23,"WhatsApp, Facebook, Instagram",43481,6447,3751,1668,383640,56.18,3.09,Bengali,27.29,Working Women,2024-10-24,Nykaa
55553,NY-CMP-56553,Social Media,College Students,16,"Facebook, Email",33530,2518,584,299,194051,227.53,1.85,Bengali,10.14,Working Women,2025-05-22,Nykaa
55554,NY-CMP-56554,Social Media,College Students,25,"YouTube, Instagram, WhatsApp",41096,5254,2570,1894,647748,35.11,8.74,English,23.65,College Students,2025-05-30,Nykaa

In [5]:
df_nykaa["channel_used"]=df_nykaa.channel_used.str.split(',')
df_nykaa_exploded=df_nykaa.explode("channel_used")

In [6]:
df_nykaa_exploded[["campaign_id","channel_used"]]

        campaign_id channel_used
0       NY-CMP-1000     WhatsApp
0       NY-CMP-1000      YouTube
1       NY-CMP-1001      YouTube
2       NY-CMP-1002     WhatsApp
2       NY-CMP-1002       Google
...             ...          ...
55553  NY-CMP-56553     Facebook
55553  NY-CMP-56553        Email
55554  NY-CMP-56554      YouTube
55554  NY-CMP-56554    Instagram
55554  NY-CMP-56554     WhatsApp

[110903 rows x 2 columns]

In [7]:
df_purplle["channel_used"]=df_purplle.channel_used.str.split(',')
df_purplle_exploded=df_purplle.explode("channel_used")
df_tira["channel_used"]=df_tira.channel_used.str.split(',')
df_tira_exploded=df_tira.explode("channel_used")

In [8]:
df_purplle_exploded[["campaign_id","channel_used"]]

        campaign_id channel_used
0       PU-CMP-1000     Facebook
0       PU-CMP-1000       Google
1       PU-CMP-1001    Instagram
1       PU-CMP-1001     WhatsApp
2       PU-CMP-1002     Facebook
...             ...          ...
55553  PU-CMP-56553     Facebook
55553  PU-CMP-56553     WhatsApp
55554  PU-CMP-56554     Facebook
55554  PU-CMP-56554    Instagram
55554  PU-CMP-56554        Email

[111098 rows x 2 columns]

In [10]:
df_nykaa_exploded["channel_used"]=df_nykaa_exploded.channel_used.str.strip()
df_purplle_exploded["channel_used"]=df_purplle_exploded.channel_used.str.strip()
df_tira_exploded["channel_used"]=df_tira_exploded.channel_used.str.strip()

In [16]:
df_nykaa_exploded=df_nykaa_exploded[["campaign_id","channel_used","brand"]]

In [17]:
df_purplle_exploded=df_purplle_exploded[["campaign_id","channel_used","brand"]]
df_tira_exploded=df_tira_exploded[["campaign_id","channel_used","brand"]]

In [19]:
df_master_exploded=pd.concat([df_nykaa_exploded,df_purplle_exploded,df_tira_exploded],ignore_index=True)

In [20]:
df_master_exploded.info()

<class 'pandas.DataFrame'>
RangeIndex: 333381 entries, 0 to 333380
Data columns (total 3 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   campaign_id   333381 non-null  str
 1   channel_used  333381 non-null  str
 2   brand         333381 non-null  str
dtypes: str(3)
memory usage: 15.5 MB

In [21]:
df_master_exploded

         campaign_id channel_used  brand
0        NY-CMP-1000     WhatsApp  Nykaa
1        NY-CMP-1000      YouTube  Nykaa
2        NY-CMP-1001      YouTube  Nykaa
3        NY-CMP-1002     WhatsApp  Nykaa
4        NY-CMP-1002       Google  Nykaa
...              ...          ...    ...
333376  TI-CMP-56552     Facebook   Tira
333377  TI-CMP-56552    Instagram   Tira
333378  TI-CMP-56553       Google   Tira
333379  TI-CMP-56553        Email   Tira
333380  TI-CMP-56554    Instagram   Tira

[333381 rows x 3 columns]

In [24]:
df_master_exploded.to_csv(r"C:\project placement\cleaned csv\exploded_data_channel.csv",index=False)